# Module Manifest

@{
    # Basic module information
    RootModule           = 'OSD.psm1'
    ModuleVersion        = '25.4.6.1'
    GUID                 = '9fe5b9b6-0224-4d87-9018-a8978529f6f5'
    Author               = 'David Segura . Gary Blok . Michael Escamilla'
    CompanyName          = 'OSD Team'
    Copyright            = '(c) 2025 OSDeploy'
    Description          = 'OSD PowerShell Module for Windows Deployment'
    
    # PowerShell compatibility
    CompatiblePSEditions = @('Desktop')
    PowerShellVersion    = '5.1'
    
    # Dependencies
    RequiredModules      = @(
        @{
            ModuleName    = 'OSD.Catalogs'
            ModuleVersion = '0.0.0.1'
            Guid          = '3f39fb21-3c97-45fc-93fc-b3b4cd958aff'
        }
    )
    
    # Processing and formatting
    FormatsToProcess     = @('.\Format\MsUpCat.Format.ps1xml')
    
    # Exports
    AliasesToExport      = '*'
    CmdletsToExport      = @()
    VariablesToExport    = @()
    FunctionsToExport    = @(
        'Add-7Zip2BootImage',
        'Add-OfflineServicingWindowsDriver',
        'Add-WindowsPackageSSU',
        'Backup-DiskToFFU',
        'Backup-MyBitLockerKeys',
        'Block-AdminUser',
        'Block-ManufacturerNeLenovo',
        'Block-NoCurl',
        'Block-NoInternet',
        'Block-PowerShellVersionLt5',
        'Block-StandardUser',
        'Block-WindowsReleaseIdLt1703',
        'Block-WindowsVersionNe10',
        'Block-WinOS',
        'Block-WinPE',
        'Clear-LocalDisk',
        'Clear-USBDisk',
        'Connect-OSDCloudAzure',
        'Connect-WinREWiFi',
        'Connect-WinREWiFiByXMLProfile',
        'Convert-EsdToFolder',
        'Convert-EsdToIso',
        'Convert-EsdToWim',
        'Convert-FolderToIso',
        'Convert-PNPDeviceIDtoGuid',
        'ConvertTo-PSKeyVaultSecret',
        'Copy-IsoToUsb',
        'Copy-PSModuleToFolder',
        'Copy-PSModuleToWim',
        'Copy-PSModuleToWindowsImage',
        'Copy-WinREWIM',
        'Dismount-MyWindowsImage',
        'Edit-AdkWinPEWIM',
        'Edit-MyWindowsImage',
        'Edit-MyWinPE',
        'Edit-OSDCloudWinPE',
        'Enable-OSDCloudODT',
        'Enable-PEWimPSGallery',
        'Enable-PEWindowsImagePSGallery',
        'Enable-SpecializeDriverPack',
        'Expand-StagedDriverPack',
        'Expand-ZTIDriverPack',
        'Export-OSDCertificatesAsReg',
        'Find-OSDCloudFile',
        'Find-OSDCloudODTFile',
        'Find-OSDCloudOfflineFile',
        'Find-OSDCloudOfflinePath',
        'Find-TextInFile',
        'Find-TextInModule',
        'Get-AzClipboard',
        'Get-AzOSDCloud',
        'Get-AzOSDTechId',
        'Get-CimVideoControllerResolution',
        'Get-CloudSecret',
        'Get-ComObjects',
        'Get-ComObjMicrosoftUpdateAutoUpdate',
        'Get-ComObjMicrosoftUpdateInstaller',
        'Get-ComObjMicrosoftUpdateServiceManager',
        'Get-DataDisk',
        'Get-DellApplicationCatalog',
        'Get-DellBiosCatalog',
        'Get-DellDriverCatalog',
        'Get-DellDriverPackCatalog',
        'Get-DellFirmwareCatalog',
        'Get-DellSystemCatalog',
        'Get-DellWinPE10DriverPack',
        'Get-DellWinPEDriverPack',
        'Get-DisplayAllScreens',
        'Get-DisplayPrimaryBitmapSize',
        'Get-DisplayPrimaryMonitorSize',
        'Get-DisplayPrimaryScaling',
        'Get-DisplayVirtualScreen',
        'Get-DownLinks',
        'Get-EnablementPackage',
        'Get-FeatureUpdate',
        'Get-GithubRawContent',
        'Get-GithubRawUrl',
        'Get-HPAccessoryCatalog',
        'Get-HPBiosCatalog',
        'Get-HPDeviceFamilyPlatformDetails',
        'Get-HPDriverCatalog',
        'Get-HPDriverPackCatalog',
        'Get-HPDriverPackLatest',
        'Get-HPFirmwareCatalog',
        'Get-HPIAJSONResult',
        'Get-HPIALatestVersion',
        'Get-HPIAXMLResult',
        'Get-HPOSSupport',
        'Get-HPPlatformCatalog',
        'Get-HPSoftPaqItems',
        'Get-HPSoftpaqListLatest',
        'Get-HPSoftwareCatalog',
        'Get-HPSystemCatalog',
        'Get-HPTPMDetermine',
        'Get-HPWinPEDriverPack',
        'Get-HyperVName',
        'Get-IntelEthernetDriverPack',
        'Get-IntelGraphicsDriverPack',
        'Get-IntelRadeonDriverPack',
        'Get-IntelWirelessDriverPack',
        'Get-LenovoBiosCatalog',
        'Get-LenovoDriverPackCatalog',
        'Get-LocalDisk',
        'Get-LocalDiskPartition',
        'Get-LocalDiskVolume',
        'Get-SurfaceDriverPackCatalog',
        'Get-MsUpCat',
        'Get-MsUpCatUpdate',
        'Get-MyBiosSerialNumber',
        'Get-MyBiosUpdate',
        'Get-MyBiosVersion',
        'Get-MyBitLockerKeyProtectors',
        'Get-MyComputerManufacturer',
        'Get-MyComputerModel',
        'Get-MyComputerProduct',
        'Get-MyDefaultAUService',
        'Get-MyDellBios',
        'Get-MyDriverPack',
        'Get-MyWindowsCapability',
        'Get-MyWindowsPackage',
        'Get-NativeMatchineImage',
        'Get-OSD',
        'Get-OSDClass',
        'Get-OSDCloudAzureResources',
        'Get-OSDCloudDriverPack',
        'Get-OSDCloudDriverPacks',
        'Get-OSDCloudOperatingSystems',
        'Get-OSDCloudOperatingSystemsIndexes',
        'Get-OSDCloudOperatingSystemsIndexMap',
        'Get-OSDCloudOSNames',
        'Get-OSDCloudTemplate',
        'Get-OSDCloudTemplateNames',
        'Get-OSDCloudVMDefaults',
        'Get-OSDCloudVMSettings',
        'Get-OSDCloudWorkspace',
        'Get-OSDDisk',
        'Get-OSDGather',
        'Get-OSDHelp',
        'Get-OSDMetrics',
        'Get-OSDPad',
        'Get-OSDPartition',
        'Get-OSDPower',
        'Get-OSDVolume',
        'Get-OSDWinEvent',
        'Get-OSDWinPE',
        'Get-PowerSettingSleepAfter',
        'Get-PowerSettingTurnMonitorOffAfter',
        'Get-PSCloudScript',
        'Get-ReAgentXml',
        'Get-RegCurrentVersion',
        'Get-ScreenPNG',
        'Get-SessionsXml',
        'Get-SetupCompleteOSDCloudUSB',
        'Get-SystemFirmwareDevice',
        'Get-SystemFirmwareResource',
        'Get-SystemFirmwareUpdate',
        'Get-TimeZoneFromIP',
        'Get-USBDisk',
        'Get-USBPartition',
        'Get-USBVolume',
        'Get-WiFiActiveProfileSSID',
        'Get-WiFiProfileKey',
        'Get-Win11Readiness',
        'Get-WindowsAdkInstallPath',
        'Get-WindowsAdkInstallVersion',
        'Get-WindowsAdkPaths',
        'Get-WindowsKitsInstallPath',
        'Get-WindowsOEMProductKey',
        'Get-WindowsUpdateDriver',
        'Get-WindowsUpdateManifests',
        'Get-WinREPartition',
        'Get-WinREWiFi',
        'Get-WSUSXML',
        'Import-MDTWinPECloudDriver',
        'Import-OSDCloudWinPEDriverMDT',
        'Initialize-OSDCloudStartnet',
        'Initialize-OSDCloudStartnetUpdate',
        'Install-AzOSDIacTools',
        'Install-BuildUpdatesFromOSCloudUSB',
        'Install-HPIA',
        'Install-ModuleHPCMSL',
        'Install-SystemFirmwareUpdate',
        'Invoke-AzOSDAzureConfig',
        'Invoke-CloudSecret',
        'Invoke-Exe',
        'Invoke-HPAnalyzer',
        'Invoke-HPDriverUpdate',
        'Invoke-HPIA',
        'Invoke-HPIAOfflineSync',
        'Invoke-HPTPMDowngrade',
        'Invoke-HPTPMDownload',
        'Invoke-HPTPMEXEDownload',
        'Invoke-HPTPMEXEInstall',
        'Invoke-MSCatalogParseDate',
        'Invoke-oobeAddNetFX3',
        'Invoke-oobeAddRSAT',
        'Invoke-oobeUpdateDrivers',
        'Invoke-oobeUpdateWindows',
        'Invoke-OSDCloud',
        'Invoke-OSDCloudDriverPackCM',
        'Invoke-OSDCloudDriverPackMDT',
        'Invoke-OSDCloudDriverPackPPKG',
        'Invoke-OSDCloudIPU',
        'Invoke-OSDInfo',
        'Invoke-OSDSpecialize',
        'Invoke-OSDSpecializeDev',
        'Invoke-SelectDataDisk',
        'Invoke-SelectFFUDisk',
        'Invoke-SelectLocalDisk',
        'Invoke-SelectLocalVolume',
        'Invoke-SelectOSDDisk',
        'Invoke-SelectOSDVolume',
        'Invoke-SelectUSBDisk',
        'Invoke-SelectUSBVolume',
        'Invoke-WebPSScript',
        'Mount-MyWindowsImage',
        'New-AdkCopyPE',
        'New-AdkISO',
        'New-BootableUSBDrive',
        'New-CAB',
        'New-CabDevelopment',
        'New-OSDCloudISO',
        'New-OSDCloudOSWimFile',
        'New-OSDCloudTemplate',
        'New-OSDCloudUSB',
        'New-OSDCloudUSBSetupCompleteTemplate',
        'New-OSDCloudVM',
        'New-OSDCloudWorkspace',
        'New-OSDCloudWorkSpaceSetupCompleteTemplate',
        'New-OSDisk',
        'New-WindowsAdkISO',
        'Remove-AppxOnline',
        'Reset-OSDCloudVMSettings',
        'Resolve-MsUrl',
        'Save-ClipboardImage',
        'Save-EnablementPackage',
        'Save-FeatureUpdate',
        'Save-MsUpCatDriver',
        'Save-MsUpCatUpdate',
        'Save-MyBiosUpdate',
        'Save-MyBitLockerExternalKey',
        'Save-MyBitLockerKeyPackage',
        'Save-MyBitLockerRecoveryPassword',
        'Save-MyDellBios',
        'Save-MyDellBiosFlash64W',
        'Save-MyDriverPack',
        'Save-OSDDownload',
        'Save-SystemFirmwareUpdate',
        'Save-WebFile',
        'Save-WinPECloudDriver',
        'Save-ZTIDriverPack',
        'Select-OSDCloudAutopilotJsonItem',
        'Select-OSDCloudFileWim',
        'Select-OSDCloudImageIndex',
        'Select-OSDCloudODTFile',
        'Set-AzClipboard',
        'Set-BitlockerRegValuesXTS256',
        'Set-BootmgrTimeout',
        'Set-ClipboardScreenshot',
        'Set-CloudSecret',
        'Set-DisRes',
        'Set-HPBIOSSetting',
        'Set-HPTPMBIOSSettings',
        'Set-HyperVName',
        'Set-LatestUpdatesASAPEnabled',
        'Set-OSDCloudTemplate',
        'Set-OSDCloudUnattendAuditMode',
        'Set-OSDCloudUnattendAuditModeAutopilot',
        'Set-OSDCloudUnattendSpecialize',
        'Set-OSDCloudUnattendSpecializeDev',
        'Set-OSDCloudVMSettings',
        'Set-OSDCloudWorkspace',
        'Set-OSDxCloudUnattendSpecialize',
        'Set-PowerSettingSleepAfter',
        'Set-PowerSettingTurnMonitorOffAfter',
        'Set-SetupCompleteBitlocker',
        'Set-SetupCompleteCreateFinish',
        'Set-SetupCompleteCreateStart',
        'Set-SetupCompleteDefenderUpdate',
        'Set-SetupCompleteHPAppend',
        'Set-SetupCompleteHyperVName',
        'Set-SetupCompleteNetFX',
        'Set-SetupCompleteOEMActivation',
        'Set-SetupCompleteOSDCloudCustom',
        'Set-SetupCompleteOSDCloudUSB',
        'Set-SetupCompleteSetWiFi',
        'Set-SetupCompleteStartWindowsUpdate',
        'Set-SetupCompleteStartWindowsUpdateDriver',
        'Set-SetupCompleteTimeZone',
        'Set-TimeZoneFromIP',
        'Set-WiFi',
        'Set-WimExecutionPolicy',
        'Set-WindowsImageExecutionPolicy',
        'Set-WindowsOEMActivation',
        'Set-WinREWiFi',
        'Show-MsSettings',
        'Show-RegistryXML',
        'Start-DiskImageGUI',
        'Start-DISMFromOSDCloudUSB',
        'Start-EjectCD',
        'Start-OOBEDeploy',
        'Start-OSDCloud',
        'Start-OSDCloudAzure',
        'Start-OSDCloudCLI',
        'Start-OSDCloudGUI',
        'Start-OSDCloudGUIDev',
        'Start-OSDCloudREAzure',
        'Start-OSDCloudToolbox',
        'Start-OSDDiskPart',
        'Start-OSDeployPad',
        'Start-OSDPad',
        'Start-OSDPadCategories',
        'Start-ScreenPNGProcess',
        'Start-WindowsUpdate',
        'Start-WindowsUpdateDriver',
        'Start-WinREWiFi',
        'Stop-ScreenPNGProcess',
        'Test-DCUSupport',
        'Test-DISMFromOSDCloudUSB',
        'Test-DynamicValidateSet',
        'Test-HPIASupport',
        'Test-HPTPMFromOSDCloudUSB',
        'Test-IsVM',
        'Test-MicrosoftUpdateCatalog',
        'Test-WebConnection',
        'Test-WindowsImage',
        'Test-WindowsImageMounted',
        'Test-WindowsImageMountPath',
        'Test-WindowsPackageCAB',
        'Unblock-WindowsUpdate',
        'Unlock-MyBitLockerExternalKey',
        'Update-DefenderStack',
        'Update-IntelDriversCatalog',
        'Update-MyDellBios',
        'Update-MyWindowsImage',
        'Update-OSDCloudUSB',
        'Use-WinPEContent',
        'Wait-WebConnection',
        'Write-CMTraceLog',
        'Get-OSDCatalogDriverPack',
        'Get-OSDCatalogDriverPacks',
        'Get-OSDCatalogOperatingSystems'
    )
    
    # Private data for the module
    PrivateData = @{
        PSData = @{
            Tags         = @('osd', 'osdeploy', 'osdcloud')
            LicenseUri   = 'https://github.com/OSDeploy/OSD/blob/master/LICENSE'
            ProjectUri   = 'https://github.com/OSDeploy/OSD'
            IconUri      = 'https://raw.githubusercontent.com/OSDeploy/OSD/master/OSD.png'
            ReleaseNotes = 'https://osd.osdeploy.com'
        }
    }
}