Import-Module OSD -Force
Get-IntelEthernetDriverPack -UpdateModuleCatalog
Get-IntelGraphicsDriverPack -UpdateModuleCatalog
Get-IntelRadeonDriverPack -UpdateModuleCatalog
Get-IntelWirelessDriverPack -UpdateModuleCatalog
Get-DellSystemCatalog -UpdateModuleCatalog
Get-HPPlatformCatalog -UpdateModuleCatalog
Get-HPSystemCatalog -UpdateModuleCatalog
Get-LenovoBiosCatalog -UpdateModuleCatalog