name: Test Operating System Parity

on:
  workflow_dispatch:
  # pull_request:
  #   paths:
  #     - '.github/workflows/test-operating-system-parity.yaml'
  #     - 'Private/core-operatingsystem/**'
  #     - 'Private/core/Test-OSDCoreOperatingSystemCloudObject.ps1'
  #     - 'Public/OSDCloudTS/Get-OSDCloudOperatingSystems.ps1'
  #     - 'core/operatingsystems/**'
  #     - 'tests/core-operatingsystem/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout OSD
        uses: actions/checkout@v5

      - name: Test with Windows PowerShell 5.1
        shell: powershell
        run: |
          Install-Module Pester -RequiredVersion 5.7.1 -Scope CurrentUser -Force -SkipPublisherCheck
          Invoke-Pester -Path '.\tests\core-operatingsystem' -Output Detailed

      - name: Test with PowerShell 7
        shell: pwsh
        run: |
          Install-Module Pester -RequiredVersion 5.7.1 -Scope CurrentUser -Force -SkipPublisherCheck
          Invoke-Pester -Path '.\tests\core-operatingsystem' -Output Detailed
